import { ContactForm } from "@/components/ContactForm";
import { Navbar } from "../components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pritchard Paper Products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <Script
            async
            src="https://www.googletagmanager.com/gtag/js?id=G-QQBZ99X6WW"
          />

          <Script id="google-analytics">
            {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}');
            `}
          </Script>
      </head>
      <body className={inter.className}>
        <div className="flex flex-col m-auto 2xl:w-[1440px] text-justify">
          <Navbar />
          {children}
          <section className="bg-[#575aa7] text-[#fafafa] py-16 px-4 flex flex-col md:flex-row">
            <ContactForm />
          </section>
          <footer>
            <p className="my-5 px-8 text-xs text-[#000000cc]">
              Pritchard Paper Products Co. LTD Copyright 2024. Developed by{" "}
              <Link href={"https://www.codeinis.io/"} target="_blank">
                Codeinis.io
              </Link>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
